#!/bin/bash
# Stops accidental commits to master/main/develop. https://gist.github.com/stefansundin/9059706
# Install:
# cd path/to/git/repo
# curl -fL -o .git/hooks/pre-commit https://gist.githubusercontent.com/stefansundin/9059706/raw/pre-commit-2
# chmod +x .git/hooks/pre-commit


BRANCH=`git rev-parse --abbrev-ref HEAD`
if [[ "$BRANCH" =~ ^(master|main|develop)$ ]]; then
    >&2 echo "You are on branch $BRANCH, direct comitting is not allowed."
    exit 2
fi

if [ "`git diff --check --cached | wc -c`" -gt 0 ]; then
    >&2 echo "Your spaces don't agree with your core.whitespace rules."
    >&2 echo 'Please run `git diff --check HEAD` to see your errors.'
    exit 3
fi


if ! command -v ruff >/dev/null 2>&1; then
    >&2 echo "Please install ruff via 'pip install ruff'."
    exit 1
else
    if ! ruff format --diff `git rev-parse --show-toplevel` >/dev/null 2>&1; then
        ruff format --diff `git rev-parse --show-toplevel`
        >&2 echo
        >&2 echo "There are problems with PEP8-compliance."
        >&2 echo 'You can check yourself by executing "ruff format --diff `git rev-parse --show-toplevel`"'
        exit 1
    fi
    if ! ruff check `git rev-parse --show-toplevel` >/dev/null 2>&1; then
        ruff check `git rev-parse --show-toplevel`
        >&2 echo
        >&2 echo "There are problems in the code."
        >&2 echo 'You can check yourself by executing "ruff check `git rev-parse --show-toplevel`"'
        exit 1
    fi
fi

if command -v clang-format >/dev/null 2>&1; then
    if ! find src -type f -regex '.*\.\(cpp\|hpp\|cc\|h\)$' -print0 \
        | xargs -0 -r clang-format --dry-run --Werror >/dev/null; then
        >&2 echo "There are problems in the C++ code's formatting."
        >&2 echo "You can check yourself by executing:"
        >&2 echo "find src -regex '.*\.\(cpp\|hpp\|cc\|h\)$' -exec clang-format --dry-run --Werror {} \;"
        exit 1
    fi
fi


exit 0
