import json

from pyscf.gto import M

from quemb.molbe.mf_interfaces._pyscf_orbital_order import Orbital
from quemb.shared.helper import argsort

with open("data/h2o_cc-pvqz_orca.json") as f:
    json_data = json.load(f)


def test_orca_parsing() -> None:
    expected = [
        Orbital(idx_atom=0, element_symbol="O", n=1, l="s", m_l="s"),
        Orbital(idx_atom=0, element_symbol="O", n=2, l="s", m_l="s"),
        Orbital(idx_atom=0, element_symbol="O", n=3, l="s", m_l="s"),
        Orbital(idx_atom=0, element_symbol="O", n=4, l="s", m_l="s"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="s", m_l="s"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="p", m_l="pz"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="p", m_l="px"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="p", m_l="py"),
        Orbital(idx_atom=0, element_symbol="O", n=2, l="p", m_l="pz"),
        Orbital(idx_atom=0, element_symbol="O", n=2, l="p", m_l="px"),
        Orbital(idx_atom=0, element_symbol="O", n=2, l="p", m_l="py"),
        Orbital(idx_atom=0, element_symbol="O", n=3, l="p", m_l="pz"),
        Orbital(idx_atom=0, element_symbol="O", n=3, l="p", m_l="px"),
        Orbital(idx_atom=0, element_symbol="O", n=3, l="p", m_l="py"),
        Orbital(idx_atom=0, element_symbol="O", n=4, l="p", m_l="pz"),
        Orbital(idx_atom=0, element_symbol="O", n=4, l="p", m_l="px"),
        Orbital(idx_atom=0, element_symbol="O", n=4, l="p", m_l="py"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="d", m_l="dz^2"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="d", m_l="dxz"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="d", m_l="dyz"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="d", m_l="dx2-y2"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="d", m_l="dxy"),
        Orbital(idx_atom=0, element_symbol="O", n=2, l="d", m_l="dz^2"),
        Orbital(idx_atom=0, element_symbol="O", n=2, l="d", m_l="dxz"),
        Orbital(idx_atom=0, element_symbol="O", n=2, l="d", m_l="dyz"),
        Orbital(idx_atom=0, element_symbol="O", n=2, l="d", m_l="dx2-y2"),
        Orbital(idx_atom=0, element_symbol="O", n=2, l="d", m_l="dxy"),
        Orbital(idx_atom=0, element_symbol="O", n=3, l="d", m_l="dz^2"),
        Orbital(idx_atom=0, element_symbol="O", n=3, l="d", m_l="dxz"),
        Orbital(idx_atom=0, element_symbol="O", n=3, l="d", m_l="dyz"),
        Orbital(idx_atom=0, element_symbol="O", n=3, l="d", m_l="dx2-y2"),
        Orbital(idx_atom=0, element_symbol="O", n=3, l="d", m_l="dxy"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="f", m_l="f+0"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="f", m_l="f+1"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="f", m_l="f-1"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="f", m_l="f+2"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="f", m_l="f-2"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="f", m_l="f+3"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="f", m_l="f-3"),
        Orbital(idx_atom=0, element_symbol="O", n=2, l="f", m_l="f+0"),
        Orbital(idx_atom=0, element_symbol="O", n=2, l="f", m_l="f+1"),
        Orbital(idx_atom=0, element_symbol="O", n=2, l="f", m_l="f-1"),
        Orbital(idx_atom=0, element_symbol="O", n=2, l="f", m_l="f+2"),
        Orbital(idx_atom=0, element_symbol="O", n=2, l="f", m_l="f-2"),
        Orbital(idx_atom=0, element_symbol="O", n=2, l="f", m_l="f+3"),
        Orbital(idx_atom=0, element_symbol="O", n=2, l="f", m_l="f-3"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="g", m_l="g+0"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="g", m_l="g+1"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="g", m_l="g-1"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="g", m_l="g+2"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="g", m_l="g-2"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="g", m_l="g+3"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="g", m_l="g-3"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="g", m_l="g+4"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="g", m_l="g-4"),
        Orbital(idx_atom=1, element_symbol="H", n=1, l="s", m_l="s"),
        Orbital(idx_atom=1, element_symbol="H", n=2, l="s", m_l="s"),
        Orbital(idx_atom=1, element_symbol="H", n=3, l="s", m_l="s"),
        Orbital(idx_atom=1, element_symbol="H", n=4, l="s", m_l="s"),
        Orbital(idx_atom=1, element_symbol="H", n=1, l="p", m_l="pz"),
        Orbital(idx_atom=1, element_symbol="H", n=1, l="p", m_l="px"),
        Orbital(idx_atom=1, element_symbol="H", n=1, l="p", m_l="py"),
        Orbital(idx_atom=1, element_symbol="H", n=2, l="p", m_l="pz"),
        Orbital(idx_atom=1, element_symbol="H", n=2, l="p", m_l="px"),
        Orbital(idx_atom=1, element_symbol="H", n=2, l="p", m_l="py"),
        Orbital(idx_atom=1, element_symbol="H", n=3, l="p", m_l="pz"),
        Orbital(idx_atom=1, element_symbol="H", n=3, l="p", m_l="px"),
        Orbital(idx_atom=1, element_symbol="H", n=3, l="p", m_l="py"),
        Orbital(idx_atom=1, element_symbol="H", n=1, l="d", m_l="dz^2"),
        Orbital(idx_atom=1, element_symbol="H", n=1, l="d", m_l="dxz"),
        Orbital(idx_atom=1, element_symbol="H", n=1, l="d", m_l="dyz"),
        Orbital(idx_atom=1, element_symbol="H", n=1, l="d", m_l="dx2-y2"),
        Orbital(idx_atom=1, element_symbol="H", n=1, l="d", m_l="dxy"),
        Orbital(idx_atom=1, element_symbol="H", n=2, l="d", m_l="dz^2"),
        Orbital(idx_atom=1, element_symbol="H", n=2, l="d", m_l="dxz"),
        Orbital(idx_atom=1, element_symbol="H", n=2, l="d", m_l="dyz"),
        Orbital(idx_atom=1, element_symbol="H", n=2, l="d", m_l="dx2-y2"),
        Orbital(idx_atom=1, element_symbol="H", n=2, l="d", m_l="dxy"),
        Orbital(idx_atom=1, element_symbol="H", n=1, l="f", m_l="f+0"),
        Orbital(idx_atom=1, element_symbol="H", n=1, l="f", m_l="f+1"),
        Orbital(idx_atom=1, element_symbol="H", n=1, l="f", m_l="f-1"),
        Orbital(idx_atom=1, element_symbol="H", n=1, l="f", m_l="f+2"),
        Orbital(idx_atom=1, element_symbol="H", n=1, l="f", m_l="f-2"),
        Orbital(idx_atom=1, element_symbol="H", n=1, l="f", m_l="f+3"),
        Orbital(idx_atom=1, element_symbol="H", n=1, l="f", m_l="f-3"),
        Orbital(idx_atom=2, element_symbol="H", n=1, l="s", m_l="s"),
        Orbital(idx_atom=2, element_symbol="H", n=2, l="s", m_l="s"),
        Orbital(idx_atom=2, element_symbol="H", n=3, l="s", m_l="s"),
        Orbital(idx_atom=2, element_symbol="H", n=4, l="s", m_l="s"),
        Orbital(idx_atom=2, element_symbol="H", n=1, l="p", m_l="pz"),
        Orbital(idx_atom=2, element_symbol="H", n=1, l="p", m_l="px"),
        Orbital(idx_atom=2, element_symbol="H", n=1, l="p", m_l="py"),
        Orbital(idx_atom=2, element_symbol="H", n=2, l="p", m_l="pz"),
        Orbital(idx_atom=2, element_symbol="H", n=2, l="p", m_l="px"),
        Orbital(idx_atom=2, element_symbol="H", n=2, l="p", m_l="py"),
        Orbital(idx_atom=2, element_symbol="H", n=3, l="p", m_l="pz"),
        Orbital(idx_atom=2, element_symbol="H", n=3, l="p", m_l="px"),
        Orbital(idx_atom=2, element_symbol="H", n=3, l="p", m_l="py"),
        Orbital(idx_atom=2, element_symbol="H", n=1, l="d", m_l="dz^2"),
        Orbital(idx_atom=2, element_symbol="H", n=1, l="d", m_l="dxz"),
        Orbital(idx_atom=2, element_symbol="H", n=1, l="d", m_l="dyz"),
        Orbital(idx_atom=2, element_symbol="H", n=1, l="d", m_l="dx2-y2"),
        Orbital(idx_atom=2, element_symbol="H", n=1, l="d", m_l="dxy"),
        Orbital(idx_atom=2, element_symbol="H", n=2, l="d", m_l="dz^2"),
        Orbital(idx_atom=2, element_symbol="H", n=2, l="d", m_l="dxz"),
        Orbital(idx_atom=2, element_symbol="H", n=2, l="d", m_l="dyz"),
        Orbital(idx_atom=2, element_symbol="H", n=2, l="d", m_l="dx2-y2"),
        Orbital(idx_atom=2, element_symbol="H", n=2, l="d", m_l="dxy"),
        Orbital(idx_atom=2, element_symbol="H", n=1, l="f", m_l="f+0"),
        Orbital(idx_atom=2, element_symbol="H", n=1, l="f", m_l="f+1"),
        Orbital(idx_atom=2, element_symbol="H", n=1, l="f", m_l="f-1"),
        Orbital(idx_atom=2, element_symbol="H", n=1, l="f", m_l="f+2"),
        Orbital(idx_atom=2, element_symbol="H", n=1, l="f", m_l="f-2"),
        Orbital(idx_atom=2, element_symbol="H", n=1, l="f", m_l="f+3"),
        Orbital(idx_atom=2, element_symbol="H", n=1, l="f", m_l="f-3"),
    ]
    computed = [
        Orbital.from_orca_label(orca_str)
        for orca_str in json_data["Molecule"]["MolecularOrbitals"]["OrbitalLabels"]
    ]

    assert computed == expected

    computed_idx = argsort(
        json_data["Molecule"]["MolecularOrbitals"]["OrbitalLabels"],
        key=Orbital.from_orca_label,
    )

    expected_idx = [
        0,
        1,
        2,
        3,
        4,
        6,
        7,
        5,
        9,
        10,
        8,
        12,
        13,
        11,
        15,
        16,
        14,
        21,
        19,
        17,
        18,
        20,
        26,
        24,
        22,
        23,
        25,
        31,
        29,
        27,
        28,
        30,
        38,
        36,
        34,
        32,
        33,
        35,
        37,
        45,
        43,
        41,
        39,
        40,
        42,
        44,
        54,
        52,
        50,
        48,
        46,
        47,
        49,
        51,
        53,
        55,
        56,
        57,
        58,
        60,
        61,
        59,
        63,
        64,
        62,
        66,
        67,
        65,
        72,
        70,
        68,
        69,
        71,
        77,
        75,
        73,
        74,
        76,
        84,
        82,
        80,
        78,
        79,
        81,
        83,
        85,
        86,
        87,
        88,
        90,
        91,
        89,
        93,
        94,
        92,
        96,
        97,
        95,
        102,
        100,
        98,
        99,
        101,
        107,
        105,
        103,
        104,
        106,
        114,
        112,
        110,
        108,
        109,
        111,
        113,
    ]
    assert computed_idx == expected_idx


def test_pyscf_parsing() -> None:
    mol = M(
        atom=[(x["ElementLabel"], x["Coords"]) for x in json_data["Molecule"]["Atoms"]],
        basis="cc-pvqz",
    )

    expected = [
        Orbital(idx_atom=0, element_symbol="O", n=1, l="s", m_l="s"),
        Orbital(idx_atom=0, element_symbol="O", n=2, l="s", m_l="s"),
        Orbital(idx_atom=0, element_symbol="O", n=3, l="s", m_l="s"),
        Orbital(idx_atom=0, element_symbol="O", n=4, l="s", m_l="s"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="s", m_l="s"),
        Orbital(idx_atom=0, element_symbol="O", n=2, l="p", m_l="px"),
        Orbital(idx_atom=0, element_symbol="O", n=2, l="p", m_l="py"),
        Orbital(idx_atom=0, element_symbol="O", n=2, l="p", m_l="pz"),
        Orbital(idx_atom=0, element_symbol="O", n=3, l="p", m_l="px"),
        Orbital(idx_atom=0, element_symbol="O", n=3, l="p", m_l="py"),
        Orbital(idx_atom=0, element_symbol="O", n=3, l="p", m_l="pz"),
        Orbital(idx_atom=0, element_symbol="O", n=4, l="p", m_l="px"),
        Orbital(idx_atom=0, element_symbol="O", n=4, l="p", m_l="py"),
        Orbital(idx_atom=0, element_symbol="O", n=4, l="p", m_l="pz"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="p", m_l="px"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="p", m_l="py"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="p", m_l="pz"),
        Orbital(idx_atom=0, element_symbol="O", n=3, l="d", m_l="dxy"),
        Orbital(idx_atom=0, element_symbol="O", n=3, l="d", m_l="dyz"),
        Orbital(idx_atom=0, element_symbol="O", n=3, l="d", m_l="dz^2"),
        Orbital(idx_atom=0, element_symbol="O", n=3, l="d", m_l="dxz"),
        Orbital(idx_atom=0, element_symbol="O", n=3, l="d", m_l="dx2-y2"),
        Orbital(idx_atom=0, element_symbol="O", n=4, l="d", m_l="dxy"),
        Orbital(idx_atom=0, element_symbol="O", n=4, l="d", m_l="dyz"),
        Orbital(idx_atom=0, element_symbol="O", n=4, l="d", m_l="dz^2"),
        Orbital(idx_atom=0, element_symbol="O", n=4, l="d", m_l="dxz"),
        Orbital(idx_atom=0, element_symbol="O", n=4, l="d", m_l="dx2-y2"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="d", m_l="dxy"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="d", m_l="dyz"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="d", m_l="dz^2"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="d", m_l="dxz"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="d", m_l="dx2-y2"),
        Orbital(idx_atom=0, element_symbol="O", n=4, l="f", m_l="f-3"),
        Orbital(idx_atom=0, element_symbol="O", n=4, l="f", m_l="f-2"),
        Orbital(idx_atom=0, element_symbol="O", n=4, l="f", m_l="f-1"),
        Orbital(idx_atom=0, element_symbol="O", n=4, l="f", m_l="f+0"),
        Orbital(idx_atom=0, element_symbol="O", n=4, l="f", m_l="f+1"),
        Orbital(idx_atom=0, element_symbol="O", n=4, l="f", m_l="f+2"),
        Orbital(idx_atom=0, element_symbol="O", n=4, l="f", m_l="f+3"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="f", m_l="f-3"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="f", m_l="f-2"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="f", m_l="f-1"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="f", m_l="f+0"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="f", m_l="f+1"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="f", m_l="f+2"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="f", m_l="f+3"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="g", m_l="g-4"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="g", m_l="g-3"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="g", m_l="g-2"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="g", m_l="g-1"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="g", m_l="g+0"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="g", m_l="g+1"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="g", m_l="g+2"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="g", m_l="g+3"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="g", m_l="g+4"),
        Orbital(idx_atom=1, element_symbol="H", n=1, l="s", m_l="s"),
        Orbital(idx_atom=1, element_symbol="H", n=2, l="s", m_l="s"),
        Orbital(idx_atom=1, element_symbol="H", n=3, l="s", m_l="s"),
        Orbital(idx_atom=1, element_symbol="H", n=4, l="s", m_l="s"),
        Orbital(idx_atom=1, element_symbol="H", n=2, l="p", m_l="px"),
        Orbital(idx_atom=1, element_symbol="H", n=2, l="p", m_l="py"),
        Orbital(idx_atom=1, element_symbol="H", n=2, l="p", m_l="pz"),
        Orbital(idx_atom=1, element_symbol="H", n=3, l="p", m_l="px"),
        Orbital(idx_atom=1, element_symbol="H", n=3, l="p", m_l="py"),
        Orbital(idx_atom=1, element_symbol="H", n=3, l="p", m_l="pz"),
        Orbital(idx_atom=1, element_symbol="H", n=4, l="p", m_l="px"),
        Orbital(idx_atom=1, element_symbol="H", n=4, l="p", m_l="py"),
        Orbital(idx_atom=1, element_symbol="H", n=4, l="p", m_l="pz"),
        Orbital(idx_atom=1, element_symbol="H", n=3, l="d", m_l="dxy"),
        Orbital(idx_atom=1, element_symbol="H", n=3, l="d", m_l="dyz"),
        Orbital(idx_atom=1, element_symbol="H", n=3, l="d", m_l="dz^2"),
        Orbital(idx_atom=1, element_symbol="H", n=3, l="d", m_l="dxz"),
        Orbital(idx_atom=1, element_symbol="H", n=3, l="d", m_l="dx2-y2"),
        Orbital(idx_atom=1, element_symbol="H", n=4, l="d", m_l="dxy"),
        Orbital(idx_atom=1, element_symbol="H", n=4, l="d", m_l="dyz"),
        Orbital(idx_atom=1, element_symbol="H", n=4, l="d", m_l="dz^2"),
        Orbital(idx_atom=1, element_symbol="H", n=4, l="d", m_l="dxz"),
        Orbital(idx_atom=1, element_symbol="H", n=4, l="d", m_l="dx2-y2"),
        Orbital(idx_atom=1, element_symbol="H", n=4, l="f", m_l="f-3"),
        Orbital(idx_atom=1, element_symbol="H", n=4, l="f", m_l="f-2"),
        Orbital(idx_atom=1, element_symbol="H", n=4, l="f", m_l="f-1"),
        Orbital(idx_atom=1, element_symbol="H", n=4, l="f", m_l="f+0"),
        Orbital(idx_atom=1, element_symbol="H", n=4, l="f", m_l="f+1"),
        Orbital(idx_atom=1, element_symbol="H", n=4, l="f", m_l="f+2"),
        Orbital(idx_atom=1, element_symbol="H", n=4, l="f", m_l="f+3"),
        Orbital(idx_atom=2, element_symbol="H", n=1, l="s", m_l="s"),
        Orbital(idx_atom=2, element_symbol="H", n=2, l="s", m_l="s"),
        Orbital(idx_atom=2, element_symbol="H", n=3, l="s", m_l="s"),
        Orbital(idx_atom=2, element_symbol="H", n=4, l="s", m_l="s"),
        Orbital(idx_atom=2, element_symbol="H", n=2, l="p", m_l="px"),
        Orbital(idx_atom=2, element_symbol="H", n=2, l="p", m_l="py"),
        Orbital(idx_atom=2, element_symbol="H", n=2, l="p", m_l="pz"),
        Orbital(idx_atom=2, element_symbol="H", n=3, l="p", m_l="px"),
        Orbital(idx_atom=2, element_symbol="H", n=3, l="p", m_l="py"),
        Orbital(idx_atom=2, element_symbol="H", n=3, l="p", m_l="pz"),
        Orbital(idx_atom=2, element_symbol="H", n=4, l="p", m_l="px"),
        Orbital(idx_atom=2, element_symbol="H", n=4, l="p", m_l="py"),
        Orbital(idx_atom=2, element_symbol="H", n=4, l="p", m_l="pz"),
        Orbital(idx_atom=2, element_symbol="H", n=3, l="d", m_l="dxy"),
        Orbital(idx_atom=2, element_symbol="H", n=3, l="d", m_l="dyz"),
        Orbital(idx_atom=2, element_symbol="H", n=3, l="d", m_l="dz^2"),
        Orbital(idx_atom=2, element_symbol="H", n=3, l="d", m_l="dxz"),
        Orbital(idx_atom=2, element_symbol="H", n=3, l="d", m_l="dx2-y2"),
        Orbital(idx_atom=2, element_symbol="H", n=4, l="d", m_l="dxy"),
        Orbital(idx_atom=2, element_symbol="H", n=4, l="d", m_l="dyz"),
        Orbital(idx_atom=2, element_symbol="H", n=4, l="d", m_l="dz^2"),
        Orbital(idx_atom=2, element_symbol="H", n=4, l="d", m_l="dxz"),
        Orbital(idx_atom=2, element_symbol="H", n=4, l="d", m_l="dx2-y2"),
        Orbital(idx_atom=2, element_symbol="H", n=4, l="f", m_l="f-3"),
        Orbital(idx_atom=2, element_symbol="H", n=4, l="f", m_l="f-2"),
        Orbital(idx_atom=2, element_symbol="H", n=4, l="f", m_l="f-1"),
        Orbital(idx_atom=2, element_symbol="H", n=4, l="f", m_l="f+0"),
        Orbital(idx_atom=2, element_symbol="H", n=4, l="f", m_l="f+1"),
        Orbital(idx_atom=2, element_symbol="H", n=4, l="f", m_l="f+2"),
        Orbital(idx_atom=2, element_symbol="H", n=4, l="f", m_l="f+3"),
    ]

    computed = [Orbital.from_pyscf_label(label) for label in mol.ao_labels()]

    assert computed == expected

    computed_idx = argsort(
        mol.ao_labels(), key=lambda label: Orbital.from_pyscf_label(label)
    )

    assert computed_idx == list(range(mol.nao))
