import json

from pyscf.gto import M

from quemb.molbe.mf_interfaces.pyscf_orbs import Orbital

with open("data/h2o_cc-pvqz_orca.json") as f:
    json_data = json.load(f)


def test_orca_parsing() -> None:
    expected = [
        Orbital(idx_atom=0, element_symbol="O", n=1, l="s", m_l="s"),
        Orbital(idx_atom=0, element_symbol="O", n=2, l="s", m_l="s"),
        Orbital(idx_atom=0, element_symbol="O", n=3, l="s", m_l="s"),
        Orbital(idx_atom=0, element_symbol="O", n=4, l="s", m_l="s"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="s", m_l="s"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="p", m_l="pz"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="p", m_l="px"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="p", m_l="py"),
        Orbital(idx_atom=0, element_symbol="O", n=2, l="p", m_l="pz"),
        Orbital(idx_atom=0, element_symbol="O", n=2, l="p", m_l="px"),
        Orbital(idx_atom=0, element_symbol="O", n=2, l="p", m_l="py"),
        Orbital(idx_atom=0, element_symbol="O", n=3, l="p", m_l="pz"),
        Orbital(idx_atom=0, element_symbol="O", n=3, l="p", m_l="px"),
        Orbital(idx_atom=0, element_symbol="O", n=3, l="p", m_l="py"),
        Orbital(idx_atom=0, element_symbol="O", n=4, l="p", m_l="pz"),
        Orbital(idx_atom=0, element_symbol="O", n=4, l="p", m_l="px"),
        Orbital(idx_atom=0, element_symbol="O", n=4, l="p", m_l="py"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="d", m_l="dz^2"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="d", m_l="dxz"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="d", m_l="dyz"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="d", m_l="dx2-y2"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="d", m_l="dxy"),
        Orbital(idx_atom=0, element_symbol="O", n=2, l="d", m_l="dz^2"),
        Orbital(idx_atom=0, element_symbol="O", n=2, l="d", m_l="dxz"),
        Orbital(idx_atom=0, element_symbol="O", n=2, l="d", m_l="dyz"),
        Orbital(idx_atom=0, element_symbol="O", n=2, l="d", m_l="dx2-y2"),
        Orbital(idx_atom=0, element_symbol="O", n=2, l="d", m_l="dxy"),
        Orbital(idx_atom=0, element_symbol="O", n=3, l="d", m_l="dz^2"),
        Orbital(idx_atom=0, element_symbol="O", n=3, l="d", m_l="dxz"),
        Orbital(idx_atom=0, element_symbol="O", n=3, l="d", m_l="dyz"),
        Orbital(idx_atom=0, element_symbol="O", n=3, l="d", m_l="dx2-y2"),
        Orbital(idx_atom=0, element_symbol="O", n=3, l="d", m_l="dxy"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="f", m_l="f+0"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="f", m_l="f+1"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="f", m_l="f-1"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="f", m_l="f+2"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="f", m_l="f-2"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="f", m_l="f+3"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="f", m_l="f-3"),
        Orbital(idx_atom=0, element_symbol="O", n=2, l="f", m_l="f+0"),
        Orbital(idx_atom=0, element_symbol="O", n=2, l="f", m_l="f+1"),
        Orbital(idx_atom=0, element_symbol="O", n=2, l="f", m_l="f-1"),
        Orbital(idx_atom=0, element_symbol="O", n=2, l="f", m_l="f+2"),
        Orbital(idx_atom=0, element_symbol="O", n=2, l="f", m_l="f-2"),
        Orbital(idx_atom=0, element_symbol="O", n=2, l="f", m_l="f+3"),
        Orbital(idx_atom=0, element_symbol="O", n=2, l="f", m_l="f-3"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="g", m_l="g+0"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="g", m_l="g+1"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="g", m_l="g-1"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="g", m_l="g+2"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="g", m_l="g-2"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="g", m_l="g+3"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="g", m_l="g-3"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="g", m_l="g+4"),
        Orbital(idx_atom=0, element_symbol="O", n=1, l="g", m_l="g-4"),
        Orbital(idx_atom=1, element_symbol="H", n=1, l="s", m_l="s"),
        Orbital(idx_atom=1, element_symbol="H", n=2, l="s", m_l="s"),
        Orbital(idx_atom=1, element_symbol="H", n=3, l="s", m_l="s"),
        Orbital(idx_atom=1, element_symbol="H", n=4, l="s", m_l="s"),
        Orbital(idx_atom=1, element_symbol="H", n=1, l="p", m_l="pz"),
        Orbital(idx_atom=1, element_symbol="H", n=1, l="p", m_l="px"),
        Orbital(idx_atom=1, element_symbol="H", n=1, l="p", m_l="py"),
        Orbital(idx_atom=1, element_symbol="H", n=2, l="p", m_l="pz"),
        Orbital(idx_atom=1, element_symbol="H", n=2, l="p", m_l="px"),
        Orbital(idx_atom=1, element_symbol="H", n=2, l="p", m_l="py"),
        Orbital(idx_atom=1, element_symbol="H", n=3, l="p", m_l="pz"),
        Orbital(idx_atom=1, element_symbol="H", n=3, l="p", m_l="px"),
        Orbital(idx_atom=1, element_symbol="H", n=3, l="p", m_l="py"),
        Orbital(idx_atom=1, element_symbol="H", n=1, l="d", m_l="dz^2"),
        Orbital(idx_atom=1, element_symbol="H", n=1, l="d", m_l="dxz"),
        Orbital(idx_atom=1, element_symbol="H", n=1, l="d", m_l="dyz"),
        Orbital(idx_atom=1, element_symbol="H", n=1, l="d", m_l="dx2-y2"),
        Orbital(idx_atom=1, element_symbol="H", n=1, l="d", m_l="dxy"),
        Orbital(idx_atom=1, element_symbol="H", n=2, l="d", m_l="dz^2"),
        Orbital(idx_atom=1, element_symbol="H", n=2, l="d", m_l="dxz"),
        Orbital(idx_atom=1, element_symbol="H", n=2, l="d", m_l="dyz"),
        Orbital(idx_atom=1, element_symbol="H", n=2, l="d", m_l="dx2-y2"),
        Orbital(idx_atom=1, element_symbol="H", n=2, l="d", m_l="dxy"),
        Orbital(idx_atom=1, element_symbol="H", n=1, l="f", m_l="f+0"),
        Orbital(idx_atom=1, element_symbol="H", n=1, l="f", m_l="f+1"),
        Orbital(idx_atom=1, element_symbol="H", n=1, l="f", m_l="f-1"),
        Orbital(idx_atom=1, element_symbol="H", n=1, l="f", m_l="f+2"),
        Orbital(idx_atom=1, element_symbol="H", n=1, l="f", m_l="f-2"),
        Orbital(idx_atom=1, element_symbol="H", n=1, l="f", m_l="f+3"),
        Orbital(idx_atom=1, element_symbol="H", n=1, l="f", m_l="f-3"),
        Orbital(idx_atom=2, element_symbol="H", n=1, l="s", m_l="s"),
        Orbital(idx_atom=2, element_symbol="H", n=2, l="s", m_l="s"),
        Orbital(idx_atom=2, element_symbol="H", n=3, l="s", m_l="s"),
        Orbital(idx_atom=2, element_symbol="H", n=4, l="s", m_l="s"),
        Orbital(idx_atom=2, element_symbol="H", n=1, l="p", m_l="pz"),
        Orbital(idx_atom=2, element_symbol="H", n=1, l="p", m_l="px"),
        Orbital(idx_atom=2, element_symbol="H", n=1, l="p", m_l="py"),
        Orbital(idx_atom=2, element_symbol="H", n=2, l="p", m_l="pz"),
        Orbital(idx_atom=2, element_symbol="H", n=2, l="p", m_l="px"),
        Orbital(idx_atom=2, element_symbol="H", n=2, l="p", m_l="py"),
        Orbital(idx_atom=2, element_symbol="H", n=3, l="p", m_l="pz"),
        Orbital(idx_atom=2, element_symbol="H", n=3, l="p", m_l="px"),
        Orbital(idx_atom=2, element_symbol="H", n=3, l="p", m_l="py"),
        Orbital(idx_atom=2, element_symbol="H", n=1, l="d", m_l="dz^2"),
        Orbital(idx_atom=2, element_symbol="H", n=1, l="d", m_l="dxz"),
        Orbital(idx_atom=2, element_symbol="H", n=1, l="d", m_l="dyz"),
        Orbital(idx_atom=2, element_symbol="H", n=1, l="d", m_l="dx2-y2"),
        Orbital(idx_atom=2, element_symbol="H", n=1, l="d", m_l="dxy"),
        Orbital(idx_atom=2, element_symbol="H", n=2, l="d", m_l="dz^2"),
        Orbital(idx_atom=2, element_symbol="H", n=2, l="d", m_l="dxz"),
        Orbital(idx_atom=2, element_symbol="H", n=2, l="d", m_l="dyz"),
        Orbital(idx_atom=2, element_symbol="H", n=2, l="d", m_l="dx2-y2"),
        Orbital(idx_atom=2, element_symbol="H", n=2, l="d", m_l="dxy"),
        Orbital(idx_atom=2, element_symbol="H", n=1, l="f", m_l="f+0"),
        Orbital(idx_atom=2, element_symbol="H", n=1, l="f", m_l="f+1"),
        Orbital(idx_atom=2, element_symbol="H", n=1, l="f", m_l="f-1"),
        Orbital(idx_atom=2, element_symbol="H", n=1, l="f", m_l="f+2"),
        Orbital(idx_atom=2, element_symbol="H", n=1, l="f", m_l="f-2"),
        Orbital(idx_atom=2, element_symbol="H", n=1, l="f", m_l="f+3"),
        Orbital(idx_atom=2, element_symbol="H", n=1, l="f", m_l="f-3"),
    ]
    computed = [
        Orbital.from_orca_label(orca_str)
        for orca_str in json_data["Molecule"]["MolecularOrbitals"]["OrbitalLabels"]
    ]

    assert computed == expected


def test_pyscf_parsing() -> None:
    mol = M(
        atom=[(x["ElementLabel"], x["Coords"]) for x in json_data["Molecule"]["Atoms"]],
        basis="cc-pvqz",
    )

    expected = [
        Orbital(idx_atom=0, element_symbol="O", n=1, l="s", m_l="s"),
        Orbital(idx_atom=0, element_symbol="O", n=2, l="s", m_l="s"),
        Orbital(idx_atom=0, element_symbol="O", n=3, l="s", m_l="s"),
        Orbital(idx_atom=0, element_symbol="O", n=4, l="s", m_l="s"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="s", m_l="s"),
        Orbital(idx_atom=0, element_symbol="O", n=2, l="p", m_l="px"),
        Orbital(idx_atom=0, element_symbol="O", n=2, l="p", m_l="py"),
        Orbital(idx_atom=0, element_symbol="O", n=2, l="p", m_l="pz"),
        Orbital(idx_atom=0, element_symbol="O", n=3, l="p", m_l="px"),
        Orbital(idx_atom=0, element_symbol="O", n=3, l="p", m_l="py"),
        Orbital(idx_atom=0, element_symbol="O", n=3, l="p", m_l="pz"),
        Orbital(idx_atom=0, element_symbol="O", n=4, l="p", m_l="px"),
        Orbital(idx_atom=0, element_symbol="O", n=4, l="p", m_l="py"),
        Orbital(idx_atom=0, element_symbol="O", n=4, l="p", m_l="pz"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="p", m_l="px"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="p", m_l="py"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="p", m_l="pz"),
        Orbital(idx_atom=0, element_symbol="O", n=3, l="d", m_l="dxy"),
        Orbital(idx_atom=0, element_symbol="O", n=3, l="d", m_l="dyz"),
        Orbital(idx_atom=0, element_symbol="O", n=3, l="d", m_l="dz^2"),
        Orbital(idx_atom=0, element_symbol="O", n=3, l="d", m_l="dxz"),
        Orbital(idx_atom=0, element_symbol="O", n=3, l="d", m_l="dx2-y2"),
        Orbital(idx_atom=0, element_symbol="O", n=4, l="d", m_l="dxy"),
        Orbital(idx_atom=0, element_symbol="O", n=4, l="d", m_l="dyz"),
        Orbital(idx_atom=0, element_symbol="O", n=4, l="d", m_l="dz^2"),
        Orbital(idx_atom=0, element_symbol="O", n=4, l="d", m_l="dxz"),
        Orbital(idx_atom=0, element_symbol="O", n=4, l="d", m_l="dx2-y2"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="d", m_l="dxy"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="d", m_l="dyz"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="d", m_l="dz^2"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="d", m_l="dxz"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="d", m_l="dx2-y2"),
        Orbital(idx_atom=0, element_symbol="O", n=4, l="f", m_l="f-3"),
        Orbital(idx_atom=0, element_symbol="O", n=4, l="f", m_l="f-2"),
        Orbital(idx_atom=0, element_symbol="O", n=4, l="f", m_l="f-1"),
        Orbital(idx_atom=0, element_symbol="O", n=4, l="f", m_l="f+0"),
        Orbital(idx_atom=0, element_symbol="O", n=4, l="f", m_l="f+1"),
        Orbital(idx_atom=0, element_symbol="O", n=4, l="f", m_l="f+2"),
        Orbital(idx_atom=0, element_symbol="O", n=4, l="f", m_l="f+3"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="f", m_l="f-3"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="f", m_l="f-2"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="f", m_l="f-1"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="f", m_l="f+0"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="f", m_l="f+1"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="f", m_l="f+2"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="f", m_l="f+3"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="g", m_l="g-4"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="g", m_l="g-3"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="g", m_l="g-2"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="g", m_l="g-1"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="g", m_l="g+0"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="g", m_l="g+1"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="g", m_l="g+2"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="g", m_l="g+3"),
        Orbital(idx_atom=0, element_symbol="O", n=5, l="g", m_l="g+4"),
        Orbital(idx_atom=1, element_symbol="H", n=1, l="s", m_l="s"),
        Orbital(idx_atom=1, element_symbol="H", n=2, l="s", m_l="s"),
        Orbital(idx_atom=1, element_symbol="H", n=3, l="s", m_l="s"),
        Orbital(idx_atom=1, element_symbol="H", n=4, l="s", m_l="s"),
        Orbital(idx_atom=1, element_symbol="H", n=2, l="p", m_l="px"),
        Orbital(idx_atom=1, element_symbol="H", n=2, l="p", m_l="py"),
        Orbital(idx_atom=1, element_symbol="H", n=2, l="p", m_l="pz"),
        Orbital(idx_atom=1, element_symbol="H", n=3, l="p", m_l="px"),
        Orbital(idx_atom=1, element_symbol="H", n=3, l="p", m_l="py"),
        Orbital(idx_atom=1, element_symbol="H", n=3, l="p", m_l="pz"),
        Orbital(idx_atom=1, element_symbol="H", n=4, l="p", m_l="px"),
        Orbital(idx_atom=1, element_symbol="H", n=4, l="p", m_l="py"),
        Orbital(idx_atom=1, element_symbol="H", n=4, l="p", m_l="pz"),
        Orbital(idx_atom=1, element_symbol="H", n=3, l="d", m_l="dxy"),
        Orbital(idx_atom=1, element_symbol="H", n=3, l="d", m_l="dyz"),
        Orbital(idx_atom=1, element_symbol="H", n=3, l="d", m_l="dz^2"),
        Orbital(idx_atom=1, element_symbol="H", n=3, l="d", m_l="dxz"),
        Orbital(idx_atom=1, element_symbol="H", n=3, l="d", m_l="dx2-y2"),
        Orbital(idx_atom=1, element_symbol="H", n=4, l="d", m_l="dxy"),
        Orbital(idx_atom=1, element_symbol="H", n=4, l="d", m_l="dyz"),
        Orbital(idx_atom=1, element_symbol="H", n=4, l="d", m_l="dz^2"),
        Orbital(idx_atom=1, element_symbol="H", n=4, l="d", m_l="dxz"),
        Orbital(idx_atom=1, element_symbol="H", n=4, l="d", m_l="dx2-y2"),
        Orbital(idx_atom=1, element_symbol="H", n=4, l="f", m_l="f-3"),
        Orbital(idx_atom=1, element_symbol="H", n=4, l="f", m_l="f-2"),
        Orbital(idx_atom=1, element_symbol="H", n=4, l="f", m_l="f-1"),
        Orbital(idx_atom=1, element_symbol="H", n=4, l="f", m_l="f+0"),
        Orbital(idx_atom=1, element_symbol="H", n=4, l="f", m_l="f+1"),
        Orbital(idx_atom=1, element_symbol="H", n=4, l="f", m_l="f+2"),
        Orbital(idx_atom=1, element_symbol="H", n=4, l="f", m_l="f+3"),
        Orbital(idx_atom=2, element_symbol="H", n=1, l="s", m_l="s"),
        Orbital(idx_atom=2, element_symbol="H", n=2, l="s", m_l="s"),
        Orbital(idx_atom=2, element_symbol="H", n=3, l="s", m_l="s"),
        Orbital(idx_atom=2, element_symbol="H", n=4, l="s", m_l="s"),
        Orbital(idx_atom=2, element_symbol="H", n=2, l="p", m_l="px"),
        Orbital(idx_atom=2, element_symbol="H", n=2, l="p", m_l="py"),
        Orbital(idx_atom=2, element_symbol="H", n=2, l="p", m_l="pz"),
        Orbital(idx_atom=2, element_symbol="H", n=3, l="p", m_l="px"),
        Orbital(idx_atom=2, element_symbol="H", n=3, l="p", m_l="py"),
        Orbital(idx_atom=2, element_symbol="H", n=3, l="p", m_l="pz"),
        Orbital(idx_atom=2, element_symbol="H", n=4, l="p", m_l="px"),
        Orbital(idx_atom=2, element_symbol="H", n=4, l="p", m_l="py"),
        Orbital(idx_atom=2, element_symbol="H", n=4, l="p", m_l="pz"),
        Orbital(idx_atom=2, element_symbol="H", n=3, l="d", m_l="dxy"),
        Orbital(idx_atom=2, element_symbol="H", n=3, l="d", m_l="dyz"),
        Orbital(idx_atom=2, element_symbol="H", n=3, l="d", m_l="dz^2"),
        Orbital(idx_atom=2, element_symbol="H", n=3, l="d", m_l="dxz"),
        Orbital(idx_atom=2, element_symbol="H", n=3, l="d", m_l="dx2-y2"),
        Orbital(idx_atom=2, element_symbol="H", n=4, l="d", m_l="dxy"),
        Orbital(idx_atom=2, element_symbol="H", n=4, l="d", m_l="dyz"),
        Orbital(idx_atom=2, element_symbol="H", n=4, l="d", m_l="dz^2"),
        Orbital(idx_atom=2, element_symbol="H", n=4, l="d", m_l="dxz"),
        Orbital(idx_atom=2, element_symbol="H", n=4, l="d", m_l="dx2-y2"),
        Orbital(idx_atom=2, element_symbol="H", n=4, l="f", m_l="f-3"),
        Orbital(idx_atom=2, element_symbol="H", n=4, l="f", m_l="f-2"),
        Orbital(idx_atom=2, element_symbol="H", n=4, l="f", m_l="f-1"),
        Orbital(idx_atom=2, element_symbol="H", n=4, l="f", m_l="f+0"),
        Orbital(idx_atom=2, element_symbol="H", n=4, l="f", m_l="f+1"),
        Orbital(idx_atom=2, element_symbol="H", n=4, l="f", m_l="f+2"),
        Orbital(idx_atom=2, element_symbol="H", n=4, l="f", m_l="f+3"),
    ]

    computed = [Orbital.from_pyscf_label(label) for label in mol.ao_labels()]

    assert computed == expected
